name: buzz_firestore
description: An Firestore implementation of Buzz Remote Repo
version: 0.0.5
homepage: https://github.com/abbas-alshafai/buzz_firestore

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^3.2.1
  cloud_functions: ^3.3.1

  buzz_repo: ^0.0.10
  buzz_utils: ^0.0.3
  buzz_result: ^0.0.1
  buzz_logger: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
