name: buzz_firestore
description: An Firestore implementation of Buzz Remote Repo
version: 0.0.1
homepage: https://github.com/abbas-alshafai/buzz_firestore

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^3.1.12
  cloud_functions: ^3.2.17

  buzz_repo: ^0.0.3
  buzz_utils: ^0.0.2
  buzz_result: ^0.0.1
  buzz_logger: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
